### ISSUE TITLE
List unlocking answer is not being evaluated

### ISSUE THREAD

**Issue by albert12132** [Cal-CS-61A-Staff/ok-client#108]
From @ksteph 

```
List Slicing > Suite 1 > Case 1
>>> x = [1, 2, 3, 4]
...
>>> x[::-1]
? [4, 3, 2,1]
-- Not quite. Try again! --

? [4, 3, 2, 1]
-- Not quite. Try again! --

? [4,3,2,1]
-- OK! --
```

This should have been handled by https://github.com/Cal-CS-61A-Staff/ok-client/pull/101; will investigate further.

**Comment by jathak** [comment]
If the user input doesn't match the expected answer exactly, then repr(eval(input)) is compared to the expected answer. However, in order for this to work, the expected answer has to be in its canonical form. I think the bug above is due to the expected answer being `[4,3,2,1]` when it should be `[4, 3, 2, 1]`.

**Comment by albert12132** [comment]
Just checked the sample test, and it seems your right. Thanks!
