### ISSUE TITLE
TypeError: int value is not subscriptable

### ISSUE THREAD

**Issue by brianhou** [Cal-CS-61A-Staff/ok-client#39]
Not sure what the issue is (no screenshots yet) but it seems to be happening to several students. The version that seems to be bundled with the homework is 1.3.8, if that affects anything.

https://piazza.com/class/i4q8ow8g8bv7oa?cid=560

**Comment by brianhou** [comment]
One student was able to fix this by uncommenting the church numerals problems.

https://piazza.com/class/i4q8ow8g8bv7oa?cid=643

**Comment by albert12132** [comment]
The issue appeared to be caused by this [line](https://github.com/Cal-CS-61A-Staff/ok-client/blob/19465d9a0b37d0e6a9411a51eac4c0d5f8413fbe/client/cli/ok.py#L187).

I think the change made in #26 makes it possible for ints to be returned by `network.dump_to_server`. @Some3141 , can you take a look at this?

**Comment by Some3141** [comment]
https://github.com/Cal-CS-61A-Staff/ok-client/blob/master/client/cli/ok.py#L199

It's on that line. You want to do something like "if response != 0 or response != 1" instead.
